site_name: tidaler
repo_url: https://github.com/maya-doshi/tidaler
site_url: https://maya-doshi.github.io/tidaler
site_description: TIDAL Media Downloader!
site_author: Maya Doshi
edit_uri: edit/master/docs/
repo_name: maya-doshi/tidaler
copyright: Maintained by <a href="https://example.com">Robby</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/maya-doshi/tidaler
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/tidaler

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
